
### Variables
@url = http://localhost:3000


### Get todos

GET {{url}}/api/v1/todos

### Create a todo

POST {{url}}/api/v1/todos
Content-Type: application/json

{
 "item": "Learn MongoDB",
 "complete": false 
}

# {
#   "item": "Learn JavaScript",
#   "complete": false
# }

### Toggle completed status of a todo

PUT {{url}}/api/v1/todos/6624549c0483d11fc8e6e21e

